### ISSUE TITLE
luminateExtend_server syntax error in IE9

### ISSUE THREAD

**Issue by chrispwolf** [noahcooper/luminateExtend#70]
luminateExtend.api() in IE9 causes a syntax error and fails. Screenshot of console error attached, remainder indicates line 1, character 1 as source of error. 
![screen shot 2015-01-30 at 4 42 27 pm](https://cloud.githubusercontent.com/assets/923700/5983918/902e3fce-a89f-11e4-97bf-6dfd01bf8db1.png)

**Comment by noahcooper** [comment]
Do you have a link to an example of a page where this is happening?

**Comment by chrispwolf** [comment]
This in-progress page:
https://www.compassionandchoices.org/what-you-can-do/donate/three-step-tester/
 
Currently, the api is only called on submission of the form.

**Comment by chrispwolf** [comment]
To make testing this easier, I have added a global function to that page, `testApiCall()`, that just pings `getDonationFormInfo` through LuminateExtend and logs the response to the console. Gets the same error on IE9 but succeeds elsewhere. 

This may be an error implementing luminateExtend_server on my part, but it works perfectly in all later browsers where I have tested it.

**Comment by noahcooper** [comment]
Chris,

It looks like the luminateExtend_server PageBuilder page was created with the TinyMCE WYSIWYG editor enabled. The WYSIWYG in an effort to be helfpul changed the markup and broke it. You'll want to disable the WYSIWYG editor and recreate that page. You can disable the WYSIWYG editor by clicking on your name in the top right corner of the Luminate Online admin UI.

**Comment by noahcooper** [comment]
One other thing I noted - in https://www.compassionandchoices.org/wp-content/themes/hotpepper_child/js/donationHandler.js, you've got the wrong non-secure path. Instead of http://cac.convio.net/site/, you should use http://support.compassionandchoices.org/site/.

**Comment by chrispwolf** [comment]
Working great. Thanks!
