### ISSUE TITLE
Cannot resolve CORSS issue.

### ISSUE THREAD

**Issue by cfern87** [noahcooper/luminateExtend#71]
Hello,
I've got a wordpress install here: http://dev-t4p.skytemple.com/. I installed the noah cooper foundation sample here: http://dev-t4p.skytemple.com/luminateTest/index.html I have the client library installed in / and in /luminateTest. I have added some js to it, but am getting COSS errors. Before I build out the html any further, I need to make sure that these errors are resolved. 

I've installed the server file on Convio here: http://www2.michaeljfox.org/site/PageNavigator/luminateExtend_server.html

Screenshot for COSS error attached. 
![unnamed](https://cloud.githubusercontent.com/assets/11179641/6354606/903e42b0-bc1e-11e4-91fb-4381848b5df0.png)

Most recently I had the following exchange with my dev: 
Me: Is there any way that we can put it directly in the /site directory? 

Him: Seems the site directory is part of Convio’s admin so no, I can’t put it directly in /site. Can’t you modify the request so that it looks for “/site/PageNavigator”? 

Any advice?

**Comment by noahcooper** [comment]
You should not be using mjff.convio.net as the domain, you should be using www2.michaeljfox.org.

**Comment by cfern87** [comment]
Thanks for the tip. Now it seems like the page is loading okay and I'm getting the log in box at the top. However, I'm trying to run the getParticipants method of the CRTeamraiserAPI and am receiving "error: insecure response." See attached image.

Unfortunately, I don't have access to the server, but I do know that luminateExtend_client.html is in both the httpdocs directory (the public html room) of the server as well as in the /luminate directory from which I'm testing. 

What's my next step? 
![2015-03-03_21h07_02](https://cloud.githubusercontent.com/assets/11179641/6476854/3ffc6cac-c1e9-11e4-8f6b-9459d6b57049.png)
