### ISSUE TITLE
CORS problem only when connecting to secure site

### ISSUE THREAD

**Issue by cfern87** [noahcooper/luminateExtend#72]
Hello Noah,
Thanks for all of your help writing this great library, and your clear and concise response to my previous issue regard CORS errors and the inability to connect to the server. It seems like I can now connect to the server, login using the loginTest method, and can logout. 

My issue now is that I cannot call any other method in which the library uses the secure site without getting the CORS error. The error looks like this: 

>XMLHttpRequest cannot load https://secure3.convio.net/mjff/site/CRTeamraiserAPI;jsessionid=C3B7E8A11ABC4EDB7FDD7EBA9F107365.app325a. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dev-t4p.skytemple.com' is therefore not allowed access.

What's odd is it seems that the login method, which also requiresAuth, doesn't have this error. Neither does my ability o log out.

Attempting to connect to the nonsecure site using https returns "insecure response."

What's interesting is that I get this when attempting to connect when using the nonsecure site as the secure site - https left off as well. 

>XMLHttpRequest cannot load https://undefinedcrteamraiserapi%3Bjsessionid%3Dc3b7e8a11abc4edb7fdd7eba9f107365.app325a/. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

Thinking that maybe the server file is configured incorrectly or something is configured incorrectly convio admin side (which unfortunately I have to go through someone to make any changes)

Your modified demo code is here: http://dev-t4p.skytemple.com/luminate/index.html
Username: susanbilotta // Password: giants17

I have confirmed that that user is an api admin.

**Comment by noahcooper** [comment]
The issue you're running into is that you're trying to access the user-side API with an administrative user. This is not possible. If you login as this admin and make a plain ol' GET request in your browser, you'll see you get this error back:

``` js
{"errorResponse":{"message":"Administrator access forbidden.","code":"3"}}
```

When this error is encountered by the API, the `Access-Control-Allow-Origin` header isn't sent back in the response.

API Admin accounts are only used when you are using the server-side API. When you're calling the API client-side, no API Admin credentials are used.
