### ISSUE TITLE
Callback function not fired on Error

### ISSUE THREAD

**Issue by seantjohnson-dev** [noahcooper/luminateExtend#82]
The error callback is not being called when the server responds back with an error. You can take a look at my case at https://childhelp.magstage.com/donate. I have the preview param set so you can try to submit and test as much as you'd like. When I type in an invalid credit card, I get a 403 from the Luminate server but no callback is fired. As you can see on the form, I have the callback named 'donateCallback'. You can find this function in 'donate-form.js' in the sources tab of your devtools. How do we get the callback to fire on error? BTW, when all of the information is correct,  the success callback gets fired properly. I just need the error to fire too so I can handle the errors properly.

**Comment by noahcooper** [comment]
@seantjohnson-dev you need to remove `suppress_response_codes` from your form. You've set this to false, which indicates that you want the API to return HTTP status codes like 403. If you remove this from your form, then the API will always return a 200 response (which is require for JavaScript to be able to handle the response data).
